const API='https://llgaeuvtrcpcvrcxkvpz.supabase.co/functions/v1/radar-meli-capture-api',ALARM='radar-auto-monitor';
async function cfg(){return await chrome.storage.local.get({autoEnabled:false,intervalMinutes:30,lastAuto:null,lastError:null,lastCount:0,queue:[],queueRunning:false,queueLog:[]})}
async function resetAlarm(){const c=await cfg();await chrome.alarms.clear(ALARM);if(c.autoEnabled)await chrome.alarms.create(ALARM,{periodInMinutes:Math.max(5,Number(c.intervalMinutes)||30)})}
async function post(r,source='checkout_extension_auto'){const resp=await fetch(API,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({product_id:r.productId,item_id:r.itemId,price:r.price,source})});const j=await resp.json().catch(()=>({}));if(!resp.ok)throw new Error(j.error||`HTTP ${resp.status}`);return j}
async function scan(){const tabs=await chrome.tabs.query({url:'https://www.mercadolivre.com.br/*'});let count=0;for(const t of tabs){if(!t.id)continue;try{const r=await chrome.tabs.sendMessage(t.id,{type:'RADAR_CAPTURE'});if(r?.ok&&r?.price&&r?.productId){await post(r);count++}}catch(_){}}
 await chrome.storage.local.set({lastAuto:new Date().toISOString(),lastCount:count,lastError:null});return{count}}
function wait(ms){return new Promise(r=>setTimeout(r,ms))}
async function waitLoaded(tabId,timeout=25000){const start=Date.now();while(Date.now()-start<timeout){try{const t=await chrome.tabs.get(tabId);if(t.status==='complete')return t}catch{}await wait(800)}throw new Error('tempo limite carregando página')}
async function clickBuy(tabId){const out=await chrome.scripting.executeScript({target:{tabId},func:()=>{const norm=s=>String(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toUpperCase();const els=[...document.querySelectorAll('button,a')];const b=els.find(e=>{const t=norm(e.innerText||e.textContent);return t.includes('COMPRAR AGORA')||t==='COMPRAR'});if(!b)return{ok:false,error:'botão Comprar agora não encontrado'};b.click();return{ok:true}}});return out?.[0]?.result}
async function processOne(entry){const productId=String(entry.productId||'').toUpperCase();if(!/^MLBU?\d{6,16}$/.test(productId))throw new Error('Product ID inválido');const url=entry.url||`https://www.mercadolivre.com.br/p/${productId}`;const tab=await chrome.tabs.create({url,active:false});try{await waitLoaded(tab.id);await wait(2500);let r=null;try{r=await chrome.tabs.sendMessage(tab.id,{type:'RADAR_CAPTURE'})}catch{}if(r?.ok&&r?.price){await post(r,'checkout_queue_auto');return{productId,price:r.price,status:'capturado'}}const buy=await clickBuy(tab.id);if(!buy?.ok)throw new Error(buy?.error||'não foi possível iniciar checkout');await wait(3500);await waitLoaded(tab.id,30000);await wait(2500);r=await chrome.tabs.sendMessage(tab.id,{type:'RADAR_CAPTURE'});if(!r?.ok||!r?.price)throw new Error('checkout abriu, mas “Você pagará” não foi encontrado');await post(r,'checkout_queue_auto');return{productId,price:r.price,status:'capturado'}}finally{try{await chrome.tabs.remove(tab.id)}catch{}}}
async function runQueue(){const c=await cfg();if(c.queueRunning)return{ok:false,error:'fila já está rodando'};const queue=(c.queue||[]).slice(0,50);await chrome.storage.local.set({queueRunning:true,queueLog:[]});const log=[];try{for(const e of queue){try{log.push(await processOne(e))}catch(err){log.push({productId:e.productId,status:'falha',error:String(err?.message||err)})}await chrome.storage.local.set({queueLog:log});await wait(3000)}return{ok:true,log}}finally{await chrome.storage.local.set({queueRunning:false,queueLog:log,lastAuto:new Date().toISOString()})}}
chrome.runtime.onInstalled.addListener(resetAlarm);chrome.runtime.onStartup.addListener(resetAlarm);chrome.alarms.onAlarm.addListener(a=>{if(a.name===ALARM)scan()});
chrome.runtime.onMessage.addListener((m,_s,send)=>{if(m?.type==='RADAR_AUTO_CONFIG'){chrome.storage.local.set({autoEnabled:!!m.enabled,intervalMinutes:Math.max(5,Number(m.intervalMinutes)||30)}).then(resetAlarm).then(()=>send({ok:true}));return true}if(m?.type==='RADAR_AUTO_STATUS'){cfg().then(send);return true}if(m?.type==='RADAR_AUTO_RUN'){scan().then(r=>send({ok:true,...r})).catch(e=>send({ok:false,error:String(e?.message||e)}));return true}if(m?.type==='RADAR_QUEUE_SET'){chrome.storage.local.set({queue:(m.queue||[]).slice(0,50)}).then(()=>send({ok:true,count:(m.queue||[]).slice(0,50).length}));return true}if(m?.type==='RADAR_QUEUE_RUN'){runQueue().then(send).catch(e=>send({ok:false,error:String(e?.message||e)}));return true}if(m?.type==='RADAR_QUEUE_STATUS'){cfg().then(send);return true}});
// Segurança: este service worker não contém nenhum comando para clicar em “Pagar e finalizar”, “Confirmar compra” ou equivalente.