const API="https://llgaeuvtrcpcvrcxkvpz.supabase.co/functions/v1/radar-client-offers";
const $=s=>document.querySelector(s);
const cards=$("#cards"),q=$("#q"),category=$("#category"),discount=$("#discount"),maxPrice=$("#maxPrice"),coupon=$("#coupon"),official=$("#official"),count=$("#count"),statusEl=$("#status");
let offers=[],timer=null,requestId=0;
const money=v=>v==null||!Number.isFinite(Number(v))?"—":Number(v).toLocaleString("pt-BR",{style:"currency",currency:"BRL"});
const esc=s=>String(s??"").replace(/[&<>"\']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","\'":"&#39;"}[c]));
function categoryOf(o){const id=String(o.category_id||"").toUpperCase(),t=String(o.title||"").toLowerCase();if(/TOOLS|DRILLS|SCREW|SAWS|GRINDERS|WRENCH|TOOL/.test(id)||/furadeira|parafusadeira|serra|esmerilhadeira|ferramenta|chave/.test(t))return"Ferramentas";if(/CELLPHONES|HEADPHONES|GAMEPADS|COMPUT|ELECTRON|CHARGERS/.test(id)||/celular|fone|controle|power bank|notebook|smartphone|bluetooth|starlink/.test(t))return"Tecnologia";if(/VEHICLE|AUTOMOT|CAR_/.test(id)||/automot|vonixx|carro|shampoo/.test(t))return"Automotivo";return"Outros";}
function images(o){const a=[o.thumbnail,o.image_url,o.imageUrl,o.image,o.photo_url,o.photo,o.product_image,o.picture];if(Array.isArray(o.images))a.push(o.images[0]);if(Array.isArray(o.pictures)&&o.pictures[0])a.push(o.pictures[0].secure_url||o.pictures[0].url);return [...new Set(a.filter(x=>typeof x==="string"&&/^https?:\/\//.test(x)))];}
function linkOf(o){return o.affiliate_url||o.permalink||""}
function attachImages(){document.querySelectorAll("img[data-images]").forEach(img=>{let list=[];try{list=JSON.parse(img.dataset.images||"[]")}catch{}let i=0;img.onerror=()=>{i++;if(list[i])img.src=list[i];else{const p=img.closest(".photo-wrap");if(p)p.innerHTML='<div class="placeholder">📦</div>'}}});}
function render(){const cat=category.value;const data=offers.filter(o=>!cat||categoryOf(o)===cat);let out="";if(data.length){for(const o of data){const catName=categoryOf(o),imgs=images(o),url=linkOf(o),disc=Number(o.discount_pct||0);let secondary="Preço atual monitorado";if(o.coupon_final_price&&Number(o.coupon_final_price)<Number(o.price))secondary="Com cupom "+money(o.coupon_final_price);else if(o.affiliate_landing_price&&o.affiliate_price_verified)secondary="Preço validado no link "+money(o.affiliate_landing_price);const facts=[o.rating?"★ "+Number(o.rating).toFixed(1):"",o.review_count?Number(o.review_count).toLocaleString("pt-BR")+" avaliações":"",o.sold_quantity?Number(o.sold_quantity).toLocaleString("pt-BR")+" vendidos":"",o.official_store?"Loja oficial":""].filter(Boolean).join(" · ");out+='<article class="card"><div class="photo-wrap"'+(url?' data-url="'+esc(url)+'"':"")+'>'+(imgs.length?'<img src="'+esc(imgs[0])+'" alt="'+esc(o.title)+'" loading="lazy" data-images=\''+esc(JSON.stringify(imgs))+'\'>':'<div class="placeholder">📦</div>')+'</div><div class="body"><span class="tag">'+esc(catName)+'</span><div class="title">'+esc(o.title)+'</div><div class="price">'+money(o.price)+'</div><div class="subprice">'+esc(secondary)+'</div>'+(facts?'<div class="facts">'+esc(facts)+'</div>':"")+'<div class="metrics"><div class="metric"><b>'+money(o.history_min_90d)+'</b><span>Mínima 90d</span></div><div class="metric"><b>'+money(o.history_median_90d)+'</b><span>Mediana 90d</span></div><div class="metric"><b>'+money(o.history_max_90d)+'</b><span>Máxima 90d</span></div></div><div class="below '+(disc>0?"":"neutral")+'">'+(disc>0?disc.toFixed(1)+"% abaixo da mediana de 90 dias":"Sem desconto relevante sobre a mediana")+'</div>'+(o.coupon_code?'<div class="couponline">Cupom: '+esc(o.coupon_code)+'</div>':"")+(url?'<a class="cta" href="'+esc(url)+'" target="_blank" rel="noopener noreferrer">Ver oferta</a>':'<span class="cta disabled">Link em validação</span>')+'</div></article>';}}else out='<div class="empty"><strong>Nenhuma oferta encontrada com esses filtros.</strong><br><small>O Radar mostra apenas produtos com avaliação mínima 4,5★ e pelo menos 30 avaliações.</small></div>';cards.innerHTML=out;count.textContent=data.length+" oferta"+(data.length===1?"":"s")+" validada"+(data.length===1?"":"s");attachImages();document.querySelectorAll(".photo-wrap[data-url]").forEach(el=>el.onclick=()=>window.open(el.dataset.url,"_blank","noopener,noreferrer"));}
async function load(){const id=++requestId;statusEl.className="status";statusEl.textContent="● Atualizando";count.textContent="Buscando ofertas reais…";const p=new URLSearchParams();if(q.value.trim())p.set("q",q.value.trim());p.set("min_discount",discount.value||"0");if(maxPrice.value)p.set("max_price",maxPrice.value);if(coupon.checked)p.set("coupon","true");if(official.checked)p.set("official","true");try{const r=await fetch(API+"?"+p.toString(),{headers:{"Accept":"application/json"},cache:"no-store"});if(!r.ok)throw new Error("http");const j=await r.json();if(id!==requestId)return;offers=Array.isArray(j.rows)?j.rows:[];statusEl.className="status ok";statusEl.textContent="● Atualizado";render()}catch(e){if(id!==requestId)return;offers=[];statusEl.className="status err";statusEl.textContent="● Indisponível";count.textContent="Radar temporariamente indisponível";cards.innerHTML='<div class="empty">Não foi possível carregar as ofertas agora. Tente novamente em instantes.</div>'}}
$("#filtersBtn").onclick=()=>$("#filters").classList.toggle("hidden");
q.addEventListener("input",()=>{clearTimeout(timer);timer=setTimeout(load,350)});
[discount,maxPrice,coupon,official].forEach(el=>el.addEventListener("change",load));
category.addEventListener("change",render);
load();
if("serviceWorker"in navigator){window.addEventListener("load",()=>navigator.serviceWorker.register("sw.js?v=3").catch(()=>{}));}